POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "adminSimpus123"
}

### logout
POST http://localhost:3000/api/auth/logout
Content-Type: application/json

### list anggota
GET http://localhost:3000/api/anggota
Content-Type: application/json

### lihat detail anggota
GET http://localhost:3000/api/anggota/94c38d2f-0b69-4b79-aeed-b423720af87f
Content-Type: application/json

### list buku
GET http://localhost:3000/api/buku
Content-Type: application/json


// Dockerfile