POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "adminSimpus123"
}

### logout
POST http://localhost:3000/api/auth/logout
Content-Type: application/json

### list anggota
GET http://localhost:3000/api/anggota
Content-Type: application/json

### lihat detail anggota
GET http://localhost:3000/api/anggota/
Content-Type: application/json

### list buku
GET http://localhost:3000/api/buku
Content-Type: application/json

### salinan buku
GET http://localhost:3000/api/salinan-buku
Content-Type: application/json

### sirkulasi/kembali
POST http://localhost:3000/api/sirkulasi/kembali
Content-Type: application/json
Cookie: simpli_auth=TOKEN_LOGIN

{
  "loanItemId": "UUID_LOAN_ITEM",
  "status": "TERSEDIA",
  "returnCondition": "Baik",
  "returnNote": "Dikembalikan lengkap"
}

### denda
POST http://localhost:3000/api/internal/jobs/fines
Authorization: Bearer 2f37709150832e3dcf227bae6c1787c2c56833979e4b6fdfb1b862bf512d26be
Content-Type: application/json

### perpanjang
POST http://localhost:3000/api/sirkulasi/perpanjang/
Content-Type: application/json

{
  "loanId": "3d2563a4-07fc-4389-9ab9-a260670bd86e",
  "additionalDays": 7,
  "notes": "Perpanjangan disetujui"
}
// Dockerfile
### list kategori
GET http://localhost:3000/api/kategori
Content-Type: application/json

### book-cover
POST http://localhost:3000/api/upload/cover
Content-Type: application/json

### PINJAMAN aktif
GET http://localhost:3000/api/sirkulasi/pinjaman-aktif
Content-Type: application/json

### PINJAMAN 
POST http://localhost:3000/api/sirkulasi/pinjam
Content-Type: application/json

{
  "studentId": "94c38d2f-0b69-4b79-aeed-b423720af87f",
  "copyIds": ["463190f6-dcbb-414e-88af-ec48ba8e38ab"],
  "dueDate": "2026-10-14T00:00:00.000Z",
  "notes": "Test pinjam"
}
