import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { Prisma } from "@/app/generated/prisma/client";

const mocks = vi.hoisted(() => ({ setting: vi.fn(), candidates: vi.fn(), item: vi.fn(), create: vi.fn(), update: vi.fn(), audit: vi.fn(), transaction: vi.fn() }));
vi.mock("@/lib/auth", () => ({ noStoreHeaders: { "Cache-Control": "no-store" } }));
vi.mock("@/lib/prisma", () => ({ prisma: { librarySetting: { findUnique: mocks.setting }, loanItem: { findMany: mocks.candidates }, $transaction: mocks.transaction } }));

const route = await import("@/app/api/internal/jobs/fines/route");
const originalCronSecret = process.env.CRON_SECRET;
const now = new Date("2026-09-30T12:00:00.000Z");
const dueDate = new Date("2026-09-25T08:00:00.000Z");
const futureDate = new Date("2026-10-05T08:00:00.000Z");
const itemId = "11111111-1111-4111-8111-111111111111";
const fineId = "22222222-2222-4222-8222-222222222222";
const rate = new Prisma.Decimal("1000");

function request(authorization?: string) { return new Request("http://localhost/api/internal/jobs/fines", { method: "POST", headers: authorization ? { authorization } : {} }); }
function candidate(id = itemId) { return { id }; }
function item(overrides: Record<string, unknown> = {}) { return { id: itemId, returnedAt: null, loan: { dueDate, status: "AKTIF" }, fine: null, ...overrides }; }
function tx() { return { loanItem: { findUnique: mocks.item }, fine: { create: mocks.create, update: mocks.update }, auditLog: { create: mocks.audit } }; }
type Tx = ReturnType<typeof tx>;
type Callback = (client: Tx) => unknown | Promise<unknown>;
async function error(response: Response, status: number, message: string) { expect(response.status).toBe(status); expect(response.headers.get("Cache-Control")).toBe("no-store"); await expect(response.json()).resolves.toEqual({ error: message }); }

beforeEach(() => {
  vi.useFakeTimers(); vi.setSystemTime(now); vi.resetAllMocks(); process.env.CRON_SECRET = "test-secret";
  mocks.setting.mockResolvedValue({ fineRatePerDay: rate }); mocks.candidates.mockResolvedValue([]); mocks.item.mockResolvedValue(item());
  mocks.create.mockResolvedValue({ id: fineId, daysLate: 5, ratePerDay: rate, amount: new Prisma.Decimal("5000"), status: "BELUM_DIBAYAR" });
  mocks.update.mockResolvedValue({ id: fineId, daysLate: 5, ratePerDay: rate, amount: new Prisma.Decimal("5000"), status: "BELUM_DIBAYAR" }); mocks.audit.mockResolvedValue({});
  mocks.transaction.mockImplementation(async (operation: Callback) => operation(tx()));
});
afterEach(() => { vi.useRealTimers(); if (originalCronSecret === undefined) delete process.env.CRON_SECRET; else process.env.CRON_SECRET = originalCronSecret; });

describe("POST /api/internal/jobs/fines", () => {
  it.each([undefined, "", "Bearer", "Bearer wrong", "Basic test-secret", "bearer test-secret"])("rejects unauthorized request: %s", async authorization => { await error(await route.POST(request(authorization)), 401, "Tidak memiliki akses."); expect(mocks.setting).not.toHaveBeenCalled(); });
  it("rejects request when CRON_SECRET is missing", async () => { delete process.env.CRON_SECRET; await error(await route.POST(request("Bearer test-secret")), 401, "Tidak memiliki akses."); });
  it("queries settings and ordered candidate batch", async () => { await route.POST(request("Bearer test-secret")); expect(mocks.setting).toHaveBeenCalledWith({ where: { key: "DEFAULT" }, select: { fineRatePerDay: true } }); expect(mocks.candidates).toHaveBeenCalledWith({ where: { returnedAt: null, loan: { status: { in: ["AKTIF", "SEBAGIAN_DIKEMBALIKAN"] }, dueDate: { lt: now } } }, orderBy: [{ loan: { dueDate: "asc" } }, { id: "asc" }], take: 500, select: { id: true } }); });
  it("returns empty batch summary", async () => { const response = await route.POST(request("Bearer test-secret")); await expect(response.json()).resolves.toEqual({ data: { processed: 0, created: 0, updated: 0, skipped: 0, hasMore: false } }); expect(mocks.transaction).not.toHaveBeenCalled(); });
  it("maps missing or failed setting query", async () => { mocks.setting.mockResolvedValue(null); await error(await route.POST(request("Bearer test-secret")), 500, "Pengaturan perpustakaan belum tersedia."); mocks.setting.mockRejectedValue(new Error("DB")); await error(await route.POST(request("Bearer test-secret")), 500, "Terjadi kesalahan pada server."); expect(mocks.candidates).not.toHaveBeenCalled(); });
  it("creates fine with setting rate and audit log", async () => { mocks.candidates.mockResolvedValue([candidate()]); const response = await route.POST(request("Bearer test-secret")); expect(response.status).toBe(200); await expect(response.json()).resolves.toEqual({ data: { processed: 1, created: 1, updated: 0, skipped: 0, hasMore: false } }); expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ loanItemId: itemId, type: "TERLAMBAT", daysLate: 5, ratePerDay: rate, amount: expect.any(Prisma.Decimal), note: "Denda otomatis keterlambatan 5 hari." }) })); expect(mocks.create.mock.calls[0][0].data.amount.toString()).toBe("5000"); expect(mocks.audit).toHaveBeenCalledWith({ data: { action: "CREATE", entityType: "Fine", entityId: fineId, newData: { id: fineId, daysLate: 5, ratePerDay: "1000", amount: "5000", status: "BELUM_DIBAYAR" } } }); });
  it("updates an existing unpaid fine with its recorded rate", async () => { const recordedRate = new Prisma.Decimal("1500"); mocks.candidates.mockResolvedValue([candidate()]); mocks.item.mockResolvedValue(item({ fine: { id: fineId, status: "BELUM_DIBAYAR", daysLate: 3, ratePerDay: recordedRate, amount: new Prisma.Decimal("4500") } })); const response = await route.POST(request("Bearer test-secret")); expect(response.status).toBe(200); expect(mocks.update).toHaveBeenCalledWith(expect.objectContaining({ where: { id: fineId }, data: expect.objectContaining({ daysLate: 5, note: "Denda otomatis keterlambatan 5 hari." }) })); expect(mocks.update.mock.calls[0][0].data.amount.toString()).toBe("7500"); expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ action: "UPDATE", oldData: expect.objectContaining({ daysLate: 3 }), newData: expect.objectContaining({ daysLate: 5 }) }) })); });
  it("creates fine for partially returned active loan", async () => { mocks.candidates.mockResolvedValue([candidate()]); mocks.item.mockResolvedValue(item({ loan: { dueDate, status: "SEBAGIAN_DIKEMBALIKAN" } })); expect((await route.POST(request("Bearer test-secret"))).status).toBe(200); expect(mocks.create).toHaveBeenCalledOnce(); });
  it.each([null, item({ returnedAt: now }), item({ loan: { dueDate, status: "SELESAI" } }), item({ loan: { dueDate: futureDate, status: "AKTIF" } }), item({ fine: { id: fineId, status: "LUNAS", daysLate: 5, ratePerDay: rate, amount: new Prisma.Decimal("5000") } }), item({ fine: { id: fineId, status: "BELUM_DIBAYAR", daysLate: 5, ratePerDay: rate, amount: new Prisma.Decimal("5000") } })])("skips ineligible candidate", async candidateItem => { mocks.candidates.mockResolvedValue([candidate()]); mocks.item.mockResolvedValue(candidateItem); const response = await route.POST(request("Bearer test-secret")); await expect(response.json()).resolves.toEqual({ data: { processed: 1, created: 0, updated: 0, skipped: 1, hasMore: false } }); expect(mocks.create).not.toHaveBeenCalled(); expect(mocks.update).not.toHaveBeenCalled(); });
  it("counts created, updated, and skipped candidates", async () => { mocks.candidates.mockResolvedValue([candidate(itemId), candidate("33333333-3333-4333-8333-333333333333"), candidate("44444444-4444-4444-8444-444444444444")]); mocks.item.mockResolvedValueOnce(item()).mockResolvedValueOnce(item({ id: "33333333-3333-4333-8333-333333333333", fine: { id: fineId, status: "BELUM_DIBAYAR", daysLate: 3, ratePerDay: rate, amount: new Prisma.Decimal("3000") } })).mockResolvedValueOnce(item({ id: "44444444-4444-4444-8444-444444444444", fine: { id: "55555555-5555-4555-8555-555555555555", status: "BELUM_DIBAYAR", daysLate: 5, ratePerDay: rate, amount: new Prisma.Decimal("5000") } })); const response = await route.POST(request("Bearer test-secret")); await expect(response.json()).resolves.toEqual({ data: { processed: 3, created: 1, updated: 1, skipped: 1, hasMore: false } }); expect(mocks.transaction).toHaveBeenCalledTimes(3); });
  it("sets hasMore for full batch", async () => { mocks.candidates.mockResolvedValue(Array.from({ length: 500 }, (_, index) => candidate(`candidate-${index}`))); mocks.transaction.mockResolvedValue("SKIPPED"); const response = await route.POST(request("Bearer test-secret")); await expect(response.json()).resolves.toEqual({ data: { processed: 500, created: 0, updated: 0, skipped: 500, hasMore: true } }); expect(mocks.transaction).toHaveBeenCalledTimes(500); });
  it("uses Serializable transaction and retries conflict work", async () => { mocks.candidates.mockResolvedValue([candidate()]); let attempts = 0; let callbackRuns = 0; const options: unknown[] = []; mocks.transaction.mockImplementation(async (...args: unknown[]) => { attempts += 1; callbackRuns += 1; options.push(args[1]); const result = await (args[0] as Callback)(tx()); if (attempts < 3) throw Object.assign(new Error("conflict"), { code: "P2034" }); return result; }); const response = await route.POST(request("Bearer test-secret")); expect(response.status).toBe(200); expect(attempts).toBe(3); expect(callbackRuns).toBe(3); expect(options).toEqual([{ isolationLevel: "Serializable" }, { isolationLevel: "Serializable" }, { isolationLevel: "Serializable" }]); });
  it("maps final conflict and database errors", async () => { mocks.candidates.mockResolvedValue([candidate()]); mocks.transaction.mockRejectedValue(Object.assign(new Error("conflict"), { code: "P2034" })); await error(await route.POST(request("Bearer test-secret")), 409, "Permintaan konflik, coba lagi."); mocks.transaction.mockRejectedValue(new Error("DB")); await error(await route.POST(request("Bearer test-secret")), 500, "Terjadi kesalahan pada server."); });
});
