import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({
  auth: vi.fn(), librarian: vi.fn(), findMany: vi.fn(), count: vi.fn(), findFirst: vi.fn(), create: vi.fn(), update: vi.fn(), book: vi.fn(), shelf: vi.fn(), loan: vi.fn(), audit: vi.fn(), transaction: vi.fn(),
}));

vi.mock("@/lib/auth", () => ({ noStoreHeaders: { "Cache-Control": "no-store" }, requireAuthenticatedUser: mocks.auth, requireLibrarian: mocks.librarian }));
vi.mock("@/lib/prisma", () => ({ prisma: { bookCopy: { findMany: mocks.findMany, count: mocks.count, findFirst: mocks.findFirst, create: mocks.create, update: mocks.update }, $transaction: mocks.transaction } }));

const listRoute = await import("@/app/api/salinan-buku/route");
const detailRoute = await import("@/app/api/salinan-buku/[id]/route");
const statusRoute = await import("@/app/api/salinan-buku/[id]/status/route");

const librarian = { id: "11111111-1111-4111-8111-111111111111", schoolId: "33333333-3333-4333-8333-333333333333", role: "PUSTAKAWAN", status: "AKTIF" };
const student = { id: "22222222-2222-4222-8222-222222222222", role: "SISWA", status: "AKTIF" };
const copyId = "33333333-3333-4333-8333-333333333333";
const bookId = "44444444-4444-4444-8444-444444444444";
const shelfId = "55555555-5555-4555-8555-555555555555";
const date = new Date("2026-09-30T08:00:00.000Z");
const acquiredAt = new Date("2026-01-15T08:00:00.000Z");

const librarianSelect = { id: true, bookId: true, shelfId: true, barcode: true, status: true, isActive: true, conditionNote: true, acquiredAt: true, createdAt: true, updatedAt: true, book: { select: { id: true, isbn: true, title: true, isActive: true } }, shelf: { select: { id: true, code: true, name: true, location: true } } } as const;
const studentSelect = { id: true, bookId: true, status: true, book: { select: { id: true, isbn: true, title: true } }, shelf: { select: { code: true, name: true, location: true } } } as const;
const statusSelect = { id: true, bookId: true, shelfId: true, barcode: true, status: true, isActive: true, conditionNote: true, acquiredAt: true, createdAt: true, updatedAt: true, book: { select: { id: true, isbn: true, title: true } }, shelf: { select: { id: true, code: true, name: true, location: true } } } as const;

const copy = { id: copyId, bookId, shelfId, barcode: "COPY-001", status: "TERSEDIA", isActive: true, conditionNote: null, acquiredAt, createdAt: date, updatedAt: date, book: { id: bookId, isbn: "9786020324787", title: "Pemrograman Dasar", isActive: true }, shelf: { id: shelfId, code: "RAK-01", name: "Rak Teknologi", location: "Lantai 1" } };
const studentCopy = { id: copyId, bookId, status: "TERSEDIA", book: { id: bookId, isbn: "9786020324787", title: "Pemrograman Dasar" }, shelf: { code: "RAK-01", name: "Rak Teknologi", location: "Lantai 1" } };
const serializedCopy = { ...copy, acquiredAt: acquiredAt.toISOString(), createdAt: date.toISOString(), updatedAt: date.toISOString() };

function req(method: string, url = "http://localhost/api/salinan-buku", body?: unknown) { return new Request(url, { method, headers: { "Content-Type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); }
function ctx(id = copyId) { return { params: Promise.resolve({ id }) }; }
function valid(overrides: Record<string, unknown> = {}) { return { bookId, shelfId, barcode: " copy-001 ", conditionNote: "Kondisi baik.", acquiredAt: acquiredAt.toISOString(), ...overrides }; }
async function error(response: Response, status: number, message: string) { expect(response.status).toBe(status); expect(response.headers.get("Cache-Control")).toBe("no-store"); await expect(response.json()).resolves.toEqual({ error: message }); }
function tx() { return { bookCopy: { findFirst: mocks.findFirst, create: mocks.create, update: mocks.update }, book: { findFirst: mocks.book }, shelf: { findUnique: mocks.shelf }, loanItem: { findFirst: mocks.loan }, auditLog: { create: mocks.audit } }; }
type Tx = ReturnType<typeof tx>;
type Callback = (client: Tx) => unknown | Promise<unknown>;

beforeEach(() => {
  vi.resetAllMocks();
  mocks.auth.mockResolvedValue({ ok: true, user: librarian }); mocks.librarian.mockResolvedValue({ ok: true, user: librarian });
  mocks.findMany.mockResolvedValue([copy]); mocks.count.mockResolvedValue(1); mocks.findFirst.mockResolvedValue(copy); mocks.create.mockResolvedValue(serializedCopy); mocks.update.mockResolvedValue(serializedCopy); mocks.book.mockResolvedValue({ id: bookId }); mocks.shelf.mockResolvedValue({ id: shelfId }); mocks.loan.mockResolvedValue(null); mocks.audit.mockResolvedValue({});
  mocks.transaction.mockImplementation(async (operation: Callback | readonly unknown[]) => typeof operation === "function" ? operation(tx()) : Promise.all(operation));
});

describe("GET /api/salinan-buku", () => {
  it("requires authentication", async () => { mocks.auth.mockResolvedValue({ ok: false, status: 401 }); await error(await listRoute.GET(req("GET")), 401, "Autentikasi diperlukan."); });
  it("returns librarian projection and pagination", async () => { const response = await listRoute.GET(req("GET")); expect(response.status).toBe(200); await expect(response.json()).resolves.toEqual({ data: [serializedCopy], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } }); expect(mocks.findMany).toHaveBeenCalledWith({ where: { isActive: true, book: { isActive: true, category: { is: { isActive: true } } } }, select: librarianSelect, orderBy: [{ createdAt: "desc" }, { id: "desc" }], skip: 0, take: 20 }); });
  it("uses student projection", async () => { mocks.auth.mockResolvedValue({ ok: true, user: student }); mocks.findMany.mockResolvedValue([studentCopy]); const response = await listRoute.GET(req("GET")); await expect(response.json()).resolves.toEqual(expect.objectContaining({ data: [studentCopy] })); expect(mocks.findMany).toHaveBeenCalledWith(expect.objectContaining({ select: studentSelect })); });
  it("applies filters and pagination", async () => { await listRoute.GET(req("GET", `http://localhost/api/salinan-buku?page=3&limit=25&bookId=${bookId}&shelfId=${shelfId}&status=DIPINJAM&search=%20program%20`)); expect(mocks.findMany).toHaveBeenCalledWith(expect.objectContaining({ skip: 50, take: 25, where: expect.objectContaining({ bookId, shelfId, status: "DIPINJAM", OR: expect.any(Array) }) })); });
  it.each(["0", "-1", "1.5", "bad"])("rejects invalid pagination %s", async value => { await error(await listRoute.GET(req("GET", `http://localhost/api/salinan-buku?page=${value}&limit=${value}`)), 422, "Parameter page tidak valid."); });
  it("rejects invalid filters and maps DB errors", async () => { await error(await listRoute.GET(req("GET", "http://localhost/api/salinan-buku?bookId=bad")), 422, "ID filter tidak valid."); await error(await listRoute.GET(req("GET", "http://localhost/api/salinan-buku?status=bad")), 422, "Status salinan buku tidak valid."); mocks.findMany.mockRejectedValue(new Error("DB")); await error(await listRoute.GET(req("GET")), 500, "Terjadi kesalahan pada server."); });
});

describe("POST /api/salinan-buku", () => {
  it.each([401, 403])("requires librarian: %s", async status => { mocks.librarian.mockResolvedValue({ ok: false, status }); await error(await listRoute.POST(req("POST", undefined, valid())), status, "Tidak memiliki akses."); });
  it("rejects malformed, array, unknown fields, and invalid data", async () => { const malformed = new Request("http://localhost/api/salinan-buku", { method: "POST", headers: { "Content-Type": "application/json" }, body: "{" }); await error(await listRoute.POST(malformed), 400, "Body JSON tidak valid."); for (const body of [null, [], "x", { ...valid(), extra: true }, valid({ barcode: "ab" }), valid({ bookId: "bad" }), valid({ acquiredAt: "bad" })]) await error(await listRoute.POST(req("POST", undefined, body)), 422, body && typeof body === "object" && !Array.isArray(body) && !("extra" in body) ? "Data salinan buku tidak valid." : "Body request tidak valid."); });
  it("normalizes and creates copy with audit log", async () => { const response = await listRoute.POST(req("POST", undefined, valid({ barcode: " copy-xyz ", conditionNote: "  Baik  " }))); expect(response.status).toBe(201); expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ barcode: "COPY-XYZ", conditionNote: "Baik", status: "TERSEDIA", isActive: true }), select: librarianSelect })); expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ userId: librarian.id, action: "CREATE", entityType: "BookCopy" }) })); });
  it("rejects missing book or shelf and maps conflicts", async () => { mocks.book.mockResolvedValue(null); await error(await listRoute.POST(req("POST", undefined, valid())), 422, "Buku tidak ditemukan atau tidak aktif."); mocks.book.mockResolvedValue({ id: bookId }); mocks.shelf.mockResolvedValue(null); await error(await listRoute.POST(req("POST", undefined, valid())), 422, "Rak tidak ditemukan."); mocks.transaction.mockRejectedValue(Object.assign(new Error("duplicate"), { code: "P2002" })); await error(await listRoute.POST(req("POST", undefined, valid())), 409, "Barcode sudah digunakan."); });
});

describe("GET /api/salinan-buku/[id]", () => {
  it("validates ID, scopes to school, returns detail, 404, and 500", async () => { mocks.auth.mockResolvedValue({ ok: true, user: librarian, schoolId: librarian.schoolId }); await error(await detailRoute.GET(req("GET"), ctx("bad")), 422, "ID salinan buku tidak valid."); const response = await detailRoute.GET(req("GET"), ctx()); expect(mocks.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ id: copyId, schoolId: librarian.schoolId }) })); await expect(response.json()).resolves.toEqual({ data: serializedCopy }); mocks.findFirst.mockResolvedValue(null); await error(await detailRoute.GET(req("GET"), ctx()), 404, "Salinan buku tidak ditemukan."); mocks.findFirst.mockRejectedValue(new Error("DB")); await error(await detailRoute.GET(req("GET"), ctx()), 500, "Terjadi kesalahan pada server."); });
  it("rejects copy from another school (IDOR)", async () => { mocks.auth.mockResolvedValue({ ok: true, user: librarian, schoolId: librarian.schoolId }); mocks.findFirst.mockResolvedValue(null); await error(await detailRoute.GET(req("GET"), ctx()), 404, "Salinan buku tidak ditemukan."); expect(mocks.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ schoolId: librarian.schoolId }) })); });
});

describe("PATCH /api/salinan-buku/[id]", () => {
  it.each([401, 403])("requires librarian: %s", async status => { mocks.librarian.mockResolvedValue({ ok: false, status }); await error(await detailRoute.PATCH(req("PATCH", undefined, { barcode: "COPY-002" }), ctx()), status, "Tidak memiliki akses."); });
  it("validates ID, body, fields, and empty patch", async () => { await error(await detailRoute.PATCH(req("PATCH", undefined, {}), ctx("bad")), 422, "ID salinan buku tidak valid."); await error(await detailRoute.PATCH(req("PATCH", undefined, []), ctx()), 422, "Body request tidak valid."); await error(await detailRoute.PATCH(req("PATCH", undefined, {}), ctx()), 422, "Tidak ada perubahan."); await error(await detailRoute.PATCH(req("PATCH", undefined, { barcode: "ab" }), ctx()), 422, "Barcode tidak valid."); await error(await detailRoute.PATCH(req("PATCH", undefined, { conditionNote: "x".repeat(1001) }), ctx()), 422, "Catatan kondisi terlalu panjang."); });
  it("updates copy and writes audit log", async () => { const response = await detailRoute.PATCH(req("PATCH", undefined, { shelfId: null, barcode: " copy-002 ", conditionNote: "  Baru  ", acquiredAt: acquiredAt.toISOString() }), ctx()); expect(response.status).toBe(200); expect(mocks.update).toHaveBeenCalledWith({ where: { id: copyId }, data: { shelfId: null, barcode: "COPY-002", conditionNote: "Baru", acquiredAt }, select: librarianSelect }); expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ action: "UPDATE", entityType: "BookCopy" }) })); });
  it("rejects absent, borrowed, missing shelf, duplicate, and conflict", async () => { mocks.findFirst.mockResolvedValue(null); await error(await detailRoute.PATCH(req("PATCH", undefined, { barcode: "COPY-002" }), ctx()), 404, "Salinan buku tidak ditemukan."); mocks.findFirst.mockResolvedValue({ ...copy, status: "DIPINJAM" }); await error(await detailRoute.PATCH(req("PATCH", undefined, { barcode: "COPY-002" }), ctx()), 409, "Salinan yang sedang dipinjam tidak dapat diubah."); mocks.findFirst.mockResolvedValue(copy); mocks.shelf.mockResolvedValue(null); await error(await detailRoute.PATCH(req("PATCH", undefined, { shelfId }), ctx()), 422, "Rak tidak ditemukan."); mocks.transaction.mockRejectedValue(Object.assign(new Error("duplicate"), { code: "P2002" })); await error(await detailRoute.PATCH(req("PATCH", undefined, { barcode: "COPY-002" }), ctx()), 409, "Barcode sudah digunakan."); });
  it("uses serializable transaction", async () => { const calls: unknown[][] = []; mocks.transaction.mockImplementation(async (...args: unknown[]) => { calls.push(args); return (args[0] as Callback)(tx()); }); const response = await detailRoute.PATCH(req("PATCH", undefined, { barcode: "COPY-002" }), ctx()); expect(response.status).toBe(200); expect(calls[0][1]).toEqual({ isolationLevel: "Serializable" }); });
});

describe("DELETE /api/salinan-buku/[id]", () => {
  it.each([401, 403])("requires librarian: %s", async status => { mocks.librarian.mockResolvedValue({ ok: false, status }); await error(await detailRoute.DELETE(req("DELETE"), ctx()), status, "Tidak memiliki akses."); });
  it("validates, archives, and writes audit log", async () => { await error(await detailRoute.DELETE(req("DELETE"), ctx("bad")), 422, "ID salinan buku tidak valid."); const response = await detailRoute.DELETE(req("DELETE"), ctx()); expect(response.status).toBe(204); expect(await response.text()).toBe(""); expect(mocks.update).toHaveBeenCalledWith({ where: { id: copyId }, data: { isActive: false }, select: librarianSelect }); expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ action: "DEACTIVATE" }) })); });
  it("rejects absent or borrowed copy and maps conflict", async () => { mocks.findFirst.mockResolvedValue(null); await error(await detailRoute.DELETE(req("DELETE"), ctx()), 404, "Salinan buku tidak ditemukan."); mocks.findFirst.mockResolvedValue({ ...copy, status: "DIPINJAM" }); await error(await detailRoute.DELETE(req("DELETE"), ctx()), 409, "Salinan yang sedang dipinjam tidak dapat diarsipkan."); mocks.findFirst.mockResolvedValue(copy); mocks.transaction.mockRejectedValue(Object.assign(new Error("conflict"), { code: "P2034" })); await error(await detailRoute.DELETE(req("DELETE"), ctx()), 409, "Permintaan konflik, coba lagi."); });
});

describe("POST /api/salinan-buku/[id]/status", () => {
  it.each([401, 403])("requires librarian: %s", async status => { mocks.librarian.mockResolvedValue({ ok: false, status }); await error(await statusRoute.POST(req("POST", undefined, { status: "RUSAK", conditionNote: "Rusak" }), ctx()), status, "Tidak memiliki akses."); });
  it("validates ID, body, status, and condition note", async () => { await error(await statusRoute.POST(req("POST", undefined, { status: "RUSAK" }), ctx("bad")), 422, "ID salinan buku tidak valid."); await error(await statusRoute.POST(req("POST", undefined, []), ctx()), 422, "Body request tidak valid."); await error(await statusRoute.POST(req("POST", undefined, { status: "BAD" }), ctx()), 422, "Status administratif tidak valid."); await error(await statusRoute.POST(req("POST", undefined, { status: "RUSAK", conditionNote: "x".repeat(1001) }), ctx()), 422, "Catatan kondisi terlalu panjang."); });
  it("requires condition note for damaged or lost status", async () => { for (const status of ["RUSAK", "HILANG"] as const) { mocks.findFirst.mockResolvedValue({ ...copy, status: "TERSEDIA" }); await error(await statusRoute.POST(req("POST", undefined, { status }), ctx()), 422, "Catatan kondisi wajib untuk status RUSAK atau HILANG."); } });
  it("rejects unchanged, invalid transition, borrowed, and active loan", async () => { mocks.findFirst.mockResolvedValue({ ...copy, status: "TERSEDIA" }); await error(await statusRoute.POST(req("POST", undefined, { status: "TERSEDIA" }), ctx()), 422, "Status salinan tidak berubah."); mocks.findFirst.mockResolvedValue({ ...copy, status: "RUSAK" }); await error(await statusRoute.POST(req("POST", undefined, { status: "HILANG", conditionNote: "Hilang" }), ctx()), 422, "Transisi status tidak diizinkan."); mocks.findFirst.mockResolvedValue({ ...copy, status: "DIPINJAM" }); await error(await statusRoute.POST(req("POST", undefined, { status: "RUSAK", conditionNote: "Rusak" }), ctx()), 409, "Salinan sedang dipinjam. Gunakan proses pengembalian."); mocks.findFirst.mockResolvedValue({ ...copy, status: "RUSAK" }); mocks.loan.mockResolvedValue({ id: "77777777-7777-4777-8777-777777777777" }); await error(await statusRoute.POST(req("POST", undefined, { status: "TERSEDIA" }), ctx()), 409, "Salinan masih memiliki peminjaman aktif."); });
  it("changes status and writes audit log", async () => { mocks.findFirst.mockResolvedValue({ ...copy, status: "TERSEDIA" }); const response = await statusRoute.POST(req("POST", undefined, { status: "RUSAK", conditionNote: "  Rusak  " }), ctx()); expect(response.status).toBe(200); expect(mocks.update).toHaveBeenCalledWith({ where: { id: copyId }, data: { status: "RUSAK", conditionNote: "Rusak" }, select: statusSelect }); expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ action: "CHANGE_STATUS", entityType: "BookCopy" }) })); });
  it("retries serializable conflict three times", async () => { let attempts = 0; const options: unknown[] = []; mocks.findFirst.mockResolvedValue({ ...copy, status: "TERSEDIA" }); mocks.transaction.mockImplementation(async (...args: unknown[]) => { options.push(args[1]); attempts += 1; if (attempts < 3) throw Object.assign(new Error("conflict"), { code: "P2034" }); return (args[0] as Callback)(tx()); }); const response = await statusRoute.POST(req("POST", undefined, { status: "RUSAK", conditionNote: "Rusak" }), ctx()); expect(response.status).toBe(200); expect(attempts).toBe(3); expect(options).toEqual([{ isolationLevel: "Serializable" }, { isolationLevel: "Serializable" }, { isolationLevel: "Serializable" }]); });
  it("maps final transaction conflict", async () => { mocks.transaction.mockRejectedValue(Object.assign(new Error("conflict"), { code: "P2034" })); await error(await statusRoute.POST(req("POST", undefined, { status: "RUSAK", conditionNote: "Rusak" }), ctx()), 409, "Permintaan konflik, coba lagi."); });
});
